# SearXNG settings
# See https://docs.searxng.org/admin/settings/settings.html

use_default_settings: true

general:
  instance_name: "LibreChat Search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  # Generate a random secret: openssl rand -hex 32
  secret_key: "CHANGE_ME_GENERATE_WITH_openssl_rand_hex_32"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true
  default_theme: simple
  
engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: wikipedia
    disabled: false
